#!/usr/bin/env python3
"""
Generate TypeScript types from OpenAPI schema.

This script fetches the OpenAPI schema from the backend API
and generates TypeScript type definitions for the frontend.

Usage:
    python scripts/generate_api_types.py [--output-path path/to/output]
    
Output:
    TypeScript type definitions in frontend/types/api.generated.ts
"""

import json
import sys
import argparse
from typing import Dict, Any, Optional
import asyncio
import httpx


class OpenAPITypeGenerator:
    """Generate TypeScript types from OpenAPI schema."""
    
    def __init__(self, schema: Dict[str, Any]):
        """Initialize with OpenAPI schema."""
        self.schema = schema
        self.generated_types: Dict[str, str] = {}
    
    def get_openapi_schema(self) -> Dict[str, Any]:
        """Extract OpenAPI schema components."""
        return self.schema.get('components', {}).get('schemas', {})
    
    def typescript_type_from_schema(self, name: str, schema: Dict[str, Any], depth: int = 0) -> str:
        """Convert OpenAPI schema to TypeScript type definition."""
        indent = "  " * depth
        lines = []
        
        # Handle references
        if '$ref' in schema:
            ref_name = schema['$ref'].split('/')[-1]
            return ref_name
        
        # Handle primitives
        if schema.get('type') == 'string':
            enum_values = schema.get('enum')
            if enum_values:
                values_str = "' | '".join(enum_values)
                return f"'{values_str}'"
            return 'string'
        elif schema.get('type') == 'number':
            return 'number'
        elif schema.get('type') == 'integer':
            return 'number'
        elif schema.get('type') == 'boolean':
            return 'boolean'
        elif schema.get('type') == 'array':
            items_type = self.typescript_type_from_schema('', schema.get('items', {}), depth)
            return f'{items_type}[]'
        elif schema.get('type') == 'object' or 'properties' in schema:
            return self._generate_object_type(schema, name, depth)
        
        # Default
        return 'any'
    
    def _generate_object_type(self, schema: Dict[str, Any], name: str, depth: int = 0) -> str:
        """Generate object interface from schema."""
        indent = "  " * depth
        next_indent = "  " * (depth + 1)
        
        properties = schema.get('properties', {})
        required_fields = set(schema.get('required', []))
        
        lines = ['{']
        for prop_name, prop_schema in properties.items():
            optional = '' if prop_name in required_fields else '?'
            prop_type = self.typescript_type_from_schema(prop_name, prop_schema, depth + 1)
            description = prop_schema.get('description', '')
            
            if description:
                lines.append(f"{next_indent}/** {description} */")
            lines.append(f"{next_indent}{prop_name}{optional}: {prop_type};")
        
        lines.append(f"{indent}}}".rstrip())
        return '\n'.join(lines)
    
    def generate_all_types(self) -> str:
        """Generate TypeScript types for all OpenAPI schemas."""
        schemas = self.get_openapi_schema()
        
        output_lines = [
            "/**",
            " * Auto-generated TypeScript types from OpenAPI schema.",
            " * Do NOT edit this file manually. Regenerate using: python scripts/generate_api_types.py",
            " *",
            " * This file contains TypeScript interfaces for all backend API responses.",
            " * It ensures type safety and consistency between frontend and backend.",
            " */",
            "",
            "// Response Models",
            ""
        ]
        
        for schema_name, schema_def in sorted(schemas.items()):
            # Skip internal schemas
            if schema_name.startswith('HTTP'):
                continue
            
            type_def = self.typescript_type_from_schema(schema_name, schema_def)
            
            description = schema_def.get('description', '')
            if description:
                output_lines.append(f"/** {description} */")
            
            output_lines.append(f"export type {schema_name} = {type_def};")
            output_lines.append("")
        
        return '\n'.join(output_lines)


async def fetch_openapi_schema(api_url: str) -> Dict[str, Any]:
    """Fetch OpenAPI schema from running backend."""
    async with httpx.AsyncClient(timeout=10.0) as client:
        try:
            response = await client.get(f"{api_url}/openapi.json")
            response.raise_for_status()
            return response.json()
        except httpx.HTTPError as e:
            print(f"Error fetching OpenAPI schema: {e}", file=sys.stderr)
            raise


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description='Generate TypeScript types from OpenAPI schema'
    )
    parser.add_argument(
        '--api-url',
        default='http://localhost:8000',
        help='Backend API URL (default: http://localhost:8000)'
    )
    parser.add_argument(
        '--output-path',
        default='frontend/types/api.generated.ts',
        help='Output file path (default: frontend/types/api.generated.ts)'
    )
    parser.add_argument(
        '--schema-file',
        help='Optional: Use local OpenAPI schema file instead of fetching from API'
    )
    
    args = parser.parse_args()
    
    try:
        # Get OpenAPI schema
        if args.schema_file:
            print(f"Loading OpenAPI schema from file: {args.schema_file}")
            with open(args.schema_file, 'r') as f:
                schema = json.load(f)
        else:
            print(f"Fetching OpenAPI schema from {args.api_url}/openapi.json...")
            schema = asyncio.run(fetch_openapi_schema(args.api_url))
        
        # Generate TypeScript types
        generator = OpenAPITypeGenerator(schema)
        typescript_code = generator.generate_all_types()
        
        # Write to file
        print(f"Writing TypeScript types to {args.output_path}...")
        with open(args.output_path, 'w') as f:
            f.write(typescript_code)
        
        print(f"✓ Successfully generated {len(schema.get('components', {}).get('schemas', {}))} type definitions")
        print(f"✓ Output written to {args.output_path}")
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
