"""Per-TF BTCUSD transformer feature pipeline (train/serve parity with Colab)."""

from feature_store.transformer_btcusd.contract import (
    CANDLE_CLASS_NAMES,
    CONTINUOUS_LABEL_COLS,
    FEATURE_COLS,
    FEATURE_CONTRACT_VERSION,
    FUSION_INPUT_RESOLUTIONS,
    FUTURE_CANDLE_COL,
    HTF_STRUCTURE_COLS,
    NATIVE_STRUCTURE_COLS,
    ONNX_OUTPUT_NAMES,
    PATH_LABEL_HORIZON_BARS,
    REGIME_NAMES,
    RESOLUTION_MINUTES,
    STRUCTURE_OUTCOME_COL,
    STRUCTURE_OUTCOME_NAMES,
    SUPPORTED_RESOLUTIONS,
    TF_KEYS,
    candle_family_from_class,
    compute_long_edge,
    compute_path_edge,
    compute_short_edge,
    default_training_config,
    feature_cols_for_resolution,
    path_favorable_adverse,
)
from feature_store.transformer_btcusd.features import (
    add_features,
    assemble_raw_frame,
    classify_candle_shape,
    prepare_raw_frame,
    add_candle_structure_features,
)
from feature_store.transformer_btcusd.inference import (
    build_candle_class_window,
    build_continuous_window,
    build_inference_window,
    load_feature_config,
    unstandardize_continuous,
)
from feature_store.transformer_btcusd.structure import (
    add_htf_structure_features,
    add_market_structure_features,
)

__all__ = [
    "CANDLE_CLASS_NAMES",
    "CONTINUOUS_LABEL_COLS",
    "FEATURE_COLS",
    "FEATURE_CONTRACT_VERSION",
    "FUTURE_CANDLE_COL",
    "HTF_STRUCTURE_COLS",
    "NATIVE_STRUCTURE_COLS",
    "ONNX_OUTPUT_NAMES",
    "PATH_LABEL_HORIZON_BARS",
    "REGIME_NAMES",
    "RESOLUTION_MINUTES",
    "STRUCTURE_OUTCOME_COL",
    "STRUCTURE_OUTCOME_NAMES",
    "SUPPORTED_RESOLUTIONS",
    "FUSION_INPUT_RESOLUTIONS",
    "TF_KEYS",
    "add_candle_structure_features",
    "add_features",
    "add_htf_structure_features",
    "add_market_structure_features",
    "assemble_raw_frame",
    "build_candle_class_window",
    "build_continuous_window",
    "build_inference_window",
    "candle_family_from_class",
    "classify_candle_shape",
    "compute_long_edge",
    "compute_path_edge",
    "compute_short_edge",
    "default_training_config",
    "feature_cols_for_resolution",
    "load_feature_config",
    "path_favorable_adverse",
    "prepare_raw_frame",
    "unstandardize_continuous",
]
